CRITICAL - 2023-05-26 12:31:43 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 26.
 1 APPPATH\Views\docentes\perfil\perfil.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:54:22 --> require(conexion.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(conexion.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:21 --> require(EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:52 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:53 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:54 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:55 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:55:55 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:29 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:30 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:30 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:30 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:30 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:31 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:31 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 12:56:31 --> require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory
in APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php on line 249.
 1 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(PruebaCalendar/EventoModel.php): Failed to open stream: No such file or directory', 'APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php', 249)
 2 APPPATH\Views\docentes\agendamientoDisponibilidad\agendamiento.php(249): require()
 3 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\agendamientoDisponibilidad\\agendamiento.php')
 4 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/agendamientoDisponibilidad/agendamiento', [], true)
 6 APPPATH\Controllers\DocenteDisponibilidad.php(29): view('docentes/agendamientoDisponibilidad/agendamiento', [...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\DocenteDisponibilidad->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\DocenteDisponibilidad))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:00:06 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:01:45 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:05:58 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(95): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:10:29 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_roles` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`)) in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-26 13:10:29 --> Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_roles` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_corto` = :nombre_corto:, `nombre_p` = :nombre_p:, `nombre_s` = :nombre_s:, `apellido_p` = :apellido_p:, `apellido_s` = :apellido_s:, `sexo` = :sexo:, `direccion` = :direccion:, `id_rol` = :id_rol:, `contrasena` = :contrasena:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:15:34 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_roles` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`)) in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-26 13:15:34 --> Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_roles` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_corto` = :nombre_corto:, `nombre_p` = :nombre_p:, `nombre_s` = :nombre_s:, `apellido_p` = :apellido_p:, `apellido_s` = :apellido_s:, `sexo` = :sexo:, `direccion` = :direccion:, `id_rol` = :id_rol:, `contrasena` = :contrasena:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:16:11 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_sexo` FOREIGN KEY (`sexo`) REFERENCES `detalles` (`id_detalles`)) in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-26 13:16:11 --> Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `usuarios_sexo` FOREIGN KEY (`sexo`) REFERENCES `detalles` (`id_detalles`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_corto` = :nombre_corto:, `nombre_p` = :nombre_p:, `nombre_s` = :nombre_s:, `apellido_p` = :apellido_p:, `apellido_s` = :apellido_s:, `sexo` = :sexo:, `direccion` = :direccion:, `id_rol` = :id_rol:, `contrasena` = :contrasena:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:17:42 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 26.
 1 APPPATH\Views\docentes\perfil\perfil.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:18:32 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 39.
 1 APPPATH\Views\docentes\perfil\perfil.php(39): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 39)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:18:52 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 26.
 1 APPPATH\Views\docentes\perfil\perfil.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:19:26 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 26.
 1 APPPATH\Views\docentes\perfil\perfil.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:19:27 --> Trying to access array offset on value of type null
in APPPATH\Views\docentes\perfil\perfil.php on line 26.
 1 APPPATH\Views\docentes\perfil\perfil.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'APPPATH\\Views\\docentes\\perfil\\perfil.php', 26)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\docentes\\perfil\\perfil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('docentes/perfil/perfil', [], true)
 5 APPPATH\Controllers\Perfiles.php(72): view('docentes/perfil/perfil', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->Docentes()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:27:33 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `roles_usuario` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`)) in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\Perfiles.php(78): CodeIgniter\Model->update('8', Array)
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-26 13:27:33 --> Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `roles_usuario` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_corto` = :nombre_corto:, `nombre_p` = :nombre_p:, `nombre_s` = :nombre_s:, `apellido_p` = :apellido_p:, `apellido_s` = :apellido_s:, `sexo` = :sexo:, `direccion` = :direccion:, `id_rol` = :id_rol:, `contrasena` = :contrasena:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Perfiles.php(78): CodeIgniter\Model->update('8', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 13:31:50 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(95): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:40:56 --> mysqli_sql_exception: Column 'sexo' cannot be null in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#11 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-05-26 13:40:56 --> Column 'sexo' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre_p`, `nombre_s`, `apellido_p`, `apellido_s`, `nombre_corto`, `direccion`, `sexo`, `tipo_de_documento`, `numero_de_documento`, `cargo`, `contrasena`, `id_rol`, `fecha_crea`) VALUES (:nombre_p:, :nombre_s:, :apellido_p:, :apellido_s:, :nombre_corto:, :direccion:, :sexo:, :tipo_de_documento:, :numero_de_documento:, :cargo:, :contrasena:, :id_rol:, :fecha_crea:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:43:36 --> mysqli_sql_exception: Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `roles_usuario` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`)) in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('UPDATE `usuario...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(943): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(756): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(70): CodeIgniter\Model->update('1', Array)
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-05-26 13:43:36 --> Cannot add or update a child row: a foreign key constraint fails (`db_citas`.`usuarios`, CONSTRAINT `roles_usuario` FOREIGN KEY (`id_rol`) REFERENCES `roles` (`id_rol`))
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2476): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_p` = :nombre_p:, `nombre_s` = :nombre_s:, `apellido_p` = :apellido_p:, `apellido_s` = :apellido_s:, `nombre_corto` = :nombre_corto:, `direccion` = :direccion:, `sexo` = :sexo:, `tipo_de_documento` = :tipo_de_documento:, `numero_de_documento` = :numero_de_documento:, `cargo` = :cargo:, `contrasena` = :contrasena:, `id_rol` = :id_rol:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(396): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\AdministrarUsuarios.php(70): CodeIgniter\Model->update('1', [...])
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:43:47 --> mysqli_sql_exception: Column 'sexo' cannot be null in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#11 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-05-26 13:43:47 --> Column 'sexo' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre_p`, `nombre_s`, `apellido_p`, `apellido_s`, `nombre_corto`, `direccion`, `sexo`, `tipo_de_documento`, `numero_de_documento`, `cargo`, `contrasena`, `id_rol`, `fecha_crea`) VALUES (:nombre_p:, :nombre_s:, :apellido_p:, :apellido_s:, :nombre_corto:, :direccion:, :sexo:, :tipo_de_documento:, :numero_de_documento:, :cargo:, :contrasena:, :id_rol:, :fecha_crea:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 13:44:43 --> mysqli_sql_exception: Column 'tipo_de_documento' cannot be null in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:295
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(295): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(691): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#11 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-05-26 13:44:43 --> Column 'tipo_de_documento' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuarios` (`nombre_p`, `nombre_s`, `apellido_p`, `apellido_s`, `nombre_corto`, `direccion`, `sexo`, `tipo_de_documento`, `numero_de_documento`, `cargo`, `contrasena`, `id_rol`, `fecha_crea`) VALUES (:nombre_p:, :nombre_s:, :apellido_p:, :apellido_s:, :nombre_corto:, :direccion:, :sexo:, :tipo_de_documento:, :numero_de_documento:, :cargo:, :contrasena:, :id_rol:, :fecha_crea:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AdministrarUsuarios.php(46): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->insertar()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:56:24 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:56:24 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:57:14 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:57:14 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:57:45 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:57:45 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:57:58 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:57:58 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:57:59 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:57:59 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:58:01 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:58:01 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:58:08 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:58:08 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:58:14 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:58:14 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*
FROM `usuarios`
WHERE `nombre_corto` = :nombre_corto:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 14:58:34 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 14:58:34 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*
FROM `usuarios`
WHERE `nombre_corto` = :nombre_corto:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 15:00:53 --> Error connecting to the database: mysqli_sql_exception: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('10.230.16.133', 'user_db', '123456789', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 15:00:53 --> Unable to connect to the database.
Main connection [MySQLi]: Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\LoginRegistrarUsuario.php(24): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginRegistrarUsuario->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginRegistrarUsuario))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 15:01:45 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 174)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('http://localhos...', 'root', '', 'db_citas', 3306, '', 0)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#5 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#8 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#11 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('http://localhos...', 'root', '', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 15:01:45 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Host desconocido. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*, `detalleSexo`.`nombre` as `nomSexo`, `detalleTipoDoc`.`nombre` as `nomTipoDoc`, `detalleCargo`.`nombre` as `nomCargo`
FROM `usuarios`
JOIN `detalles` as `detalleSexo` ON `detalleSexo`.`id_detalles` = `usuarios`.`sexo`
JOIN `detalles` as `detalleTipoDoc` ON `detalleTipoDoc`.`id_detalles` = `usuarios`.`tipo_de_documento`
JOIN `detalles` as `detalleCargo` ON `detalleCargo`.`id_detalles` = `usuarios`.`cargo`
WHERE `usuarios`.`estado` = :usuarios.estado:', [...], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(49): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\AdministrarUsuarios.php(28): App\Models\AdministradorModels\UsuariosModel->obtenerUsuariosTodo('A')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\AdministrarUsuarios->index()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdministrarUsuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-05-26 15:02:09 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 174)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('http://localhos...', 'root', '', 'db_citas', 3306, '', 0)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#5 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#8 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#11 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('http://localhos...', 'root', '', 'db_citas', 3306, '', 0)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#4 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#10 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo failed: Host desconocido.  in C:\xampp\htdocs\Agendamiento-Citas\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Agendamiento-Citas\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuario...', Array, false)
#3 C:\xampp\htdocs\Agendamiento-Citas\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Agendamiento-Citas\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\Agendamiento-Citas\app\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\Agendamiento-Citas\app\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
#7 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
#8 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
#9 C:\xampp\htdocs\Agendamiento-Citas\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Agendamiento-Citas\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-05-26 15:02:09 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo failed: Host desconocido. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `usuarios`.*
FROM `usuarios`
WHERE `nombre_corto` = :nombre_corto:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\AdministradorModels\UsuariosModel.php(127): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\LoginSignin.php(75): App\Models\AdministradorModels\UsuariosModel->Auth_usuario('sadmin')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\LoginSignin->auth()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginSignin))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 15:04:19 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(91): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 15:08:16 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(91): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 15:11:13 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(91): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-05-26 15:12:21 --> Updates are not allowed unless they contain a "where" or "like" clause.
in SYSTEMPATH\Model.php on line 391.
 1 SYSTEMPATH\BaseModel.php(943): CodeIgniter\Model->doUpdate(null, [...])
 2 SYSTEMPATH\Model.php(756): CodeIgniter\BaseModel->update(null, [...])
 3 APPPATH\Controllers\Perfiles.php(91): CodeIgniter\Model->update(null, [...])
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Perfiles->actualizar()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Perfiles))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
